builds:
  - binary: github-ratelimit-exporter
    id: github-ratelimit-exporter
    main: .
    goarch:
    - amd64
    goos:
    - darwin
    - linux
    env:
      - CGO_ENABLED=0

dockers:
  - dockerfile: Dockerfile-goreleaser
    binaries:
    - github-ratelimit-exporter
    image_templates:
    - "quay.io/lunarway/github-ratelimit-exporter:latest"
    - "quay.io/lunarway/github-ratelimit-exporter:{{ .Tag }}"

archives:
  - id: archives
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386


checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
