builds:
  - env:
    - CGO_ENABLED=0

  dockers:
  - dockerfile: Dockerfile-goreleaser
    image_templates:
    - "quay.io/lunarway/github-ratelimit-exporter:latest"
    - "quay.io/lunarway/github-ratelimit-exporter:v{{ .Major }}"
    - "quay.io/lunarway/github-ratelimit-exporter:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/lunarway/github-ratelimit-exporter:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

  archives:
    - format: binary
      name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
      replacements:
        darwin: darwin
        linux: linux
        windows: windows
        386: i386

  checksum:
    name_template: '{{ .ProjectName }}-checksums.txt'

  snapshot:
    name_template: "git-{{.Commit}}"

  release:
    name_template: "v{{.Version}}"

  changelog:
    sort: asc
    filters:
      exclude:
      - '^docs:'
      - '^test:'
