language: go
go:
  - 1.7
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get gopkg.in/tylerb/graceful.v1

script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

after_success:
  - ls -ltR
  - |
    if [ "$TRAVIS_TAG" ]; then
      release.sh $GH_USERNAME $GH_TOKEN $TRAVIS_TAG
    fi

# vim:set et ts=2 sw=2:
