language: go
go:
  - 1.3
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
  provider: script
  script: release.sh $GH_USERNAME $GH_TOKEN $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true

# vim:set et ts=2 sw=2:
